name: CI Workflow
on:
  push:
  banches:
    - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu
    steps:
      - name: Checkout code
      uses: actions/checkout@v2
      - name: step2
      uses: appleboy/ssh-action@1.2.0
      with:
        host: ${{secrets.MY_HOST}}
        username: ${{secrets.MY_USER}}
        key: ${{secrets.SSH_KEY}}
        script_path: ".github/scripts/main.sh"






